apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-app-graphql-beta
  labels:
    app: todo
    tier: backend
spec:
  template:
    metadata:
      labels:
        app: todo
        tier: backend
        channel: beta
    spec:
      containers:
        - image: gcr.io/workshops-mikebild/todo-app-graphql:v1.1.0
          name: todo-app-graphql
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: DATABASEURL
              value: 'http://couchdb-service:5984/todos'
