apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - name: simple-job
          image: gcr.io/workshops-mikebild/simple-job:v1.0.0
          command: ['npm', 'start']
      restartPolicy: Never
