apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-app-v1
  labels:
    app: ingress-app-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-app-v1
    spec:
      containers:
        - image: gcr.io/workshops-mikebild/ingress-app:v1.0.0
          name: ingress-app-v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
          readinessProbe:
            httpGet:
              path: /api/1.0.0/info
              port: 8080
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
