apiVersion: v1
kind: Service
metadata:
  name: ingress-app-v1
  labels:
    app: ingress-app-v1
spec:
  selector:
    app: ingress-app-v1
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: v1-http
  sessionAffinity: ClientIP
