apiVersion: v1
kind: Service
metadata:
  name: auth-app
  labels:
    app: auth
    tier: frontend
spec:
  selector:
    app: auth
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
