apiVersion: v1
kind: Service
metadata:
  name: files-app
  labels:
    app: files
    tier: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: files-app.workshops.mikebild.com.
spec:
  selector:
    app: files
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
