apiVersion: v1
kind: Service
metadata:
  name: todo-app-couchdb
  labels:
    app: todo
    tier: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: todo-app-couchdb.workshops.mikebild.com.
spec:
  selector:
    app: todo
    tier: database
  type: LoadBalancer
  ports:
    - port: 5984
      targetPort: 5984
